# Generated by Django 5.2 on 2025-05-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0003_orders_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expected_date',
            field=models.DateField(null=True),
        ),
    ]
